import type { BookingPathwayRoute } from './BookingPathwayRoute';
import type { Chair } from './Chair';
import type { ChairService } from './ChairService';
import type { ChairType } from './ChairType';
import type { Company } from './Company';
import type { Currency } from './Currency';
import type { GeoCity } from './GeoCity';
import type { GeoCountry } from './GeoCountry';
import type { Location } from './Location';
import type { OpenHourType } from './OpenHourType';
import type { Salon } from './Salon';
import type { SalonOpenHour } from './SalonOpenHour';
import type { Service } from './Service';
import type { ServiceBookingCompletionRule } from './ServiceBookingCompletionRule';
import type { ServiceImage } from './ServiceImage';
import type { ServicePrice } from './ServicePrice';
import type { ServicePriceType } from './ServicePriceType';
import type { ServiceStage } from './ServiceStage';
import type { ServiceStageRoleType } from './ServiceStageRoleType';
import type { Session } from './Session';
import type { Staff } from './Staff';
import type { StaffRegistration } from './StaffRegistration';
import type { StaffRole } from './StaffRole';
import type { StaffService } from './StaffService';
import type { TemporalDuration } from './TemporalDuration';

export interface Setup {
  bookingPathwayRoutes: BookingPathwayRoute[];
  chairs: Chair[];
  chairServices: ChairService[];
  chairTypes: ChairType[];
  company: Company;
  currencies: Currency[];
  geoCities: GeoCity[];
  geoCountries: GeoCountry[];
  locations: Location[];
  openHourTypes: OpenHourType[];
  salons: Salon[];
  salonImages: [];
  salonImageTypes: [];
  salonOpenHours: SalonOpenHour[];
  services: Service[];
  serviceBookingCompletionRules: ServiceBookingCompletionRule[];
  serviceImages: ServiceImage[];
  servicePrices: ServicePrice[];
  servicePriceTypes: ServicePriceType[];
  serviceStages: ServiceStage[];
  serviceStageRoleTypes: ServiceStageRoleType[];
  session: Session;
  staff: Staff[];
  staffRoles: StaffRole[];
  staffRegistrations: StaffRegistration[];
  staffServices: StaffService[];
  temporalDurations: TemporalDuration[];
}
